# A GitHub workflow that:
# - Runs on each of Linux, Windows, and MacOS
# - On each platform, runs pnpm install & pnpm build. In each case that results in an output file named by platform: `pixel-checksum.${'linux'|'win32'|'darwin'}.node
#   - Each of these is stored
# - After all platform-specific builds are made, they are all collected in a final step for publishing as a package on Linux via `pnpm install && pnpm build && pnpm test && pnpm publish`

name: Build & Publish

on:
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    name: Build (${ { matrix.platform } })
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win32
          - os: macos-latest
            platform: darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Upload platform artifact
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: "error"
          name: compiled-${{matrix.platform}}
          path: pixel-checksum.${{ matrix.platform }}.node

  publish:
    name: Publish package (linux)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v7

      - name: List files
        run: ls -l

      - name: Make executable
        run: chmod +x compiled-*/*

      - name: Move to root
        run: mv compiled-*/* ./

      - name: List files
        run: ls -l

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4

      - name: Avoid surprises
        run: pnpm test

      - name: Publish to registry
        run: pnpm publish --access public
